server:
  port: 9002

spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:h2:mem:memdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console.enabled: true

    
#spring:
#  datasource:
#    url: jdbc:postgresql://${TRAINING_DB_ENDPOINT}:5432/socialMediaDB    #${TRAINING_DB_APPDB}
#    username: ${TRAINING_DB_USERNAME}
#    password: ${TRAINING_DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
=======
    url: jdbc:postgresql://${TRAINING_DB_ENDPOINT}/socialMedia
    username: ${TRAINING_DB_USERNAME}
    password: ${TRAINING_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
   init:
      data-locations:
      - classpath:./data.sql
      mode: always
    
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
>>>>>>> 082580ad554b091a7de6cf5821262e6b7f76b798
