server:
  port: 9002

spring:
  datasource:
    url: jdbc:postgresql://${TRAINING_DB_ENDPOINT}/socialMedia
    username: ${TRAINING_DB_USERNAME}
    password: ${TRAINING_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      data-locations:
        - classpath:./data.sql
      mode: always

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
<<<<<<< HEAD
      ddl-auto: create

=======
     ddl-auto: create
>>>>>>> 914039c36bd1feda3bdd5b7c13d89574703c17c9
