server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:memdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console.enabled: true

    
#spring:
#  datasource:
#    url: jdbc:postgresql://${TRAINING_DB_ENDPOINT}:5432/socialMediaDB    #${TRAINING_DB_APPDB}
#    username: ${TRAINING_DB_USERNAME}
#    password: ${TRAINING_DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver