server:
  port: 9002

spring:
  datasource:
    url: jdbc:postgresql://${TRAINING_DB_ENDPOINT}/socialMedia
    username: ${TRAINING_DB_USERNAME}
    password: ${TRAINING_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
   init:
      data-locations:
      - classpath:./data.sql
      mode: always
    
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create