server:
  port: 9002

spring:
  datasource:
    url: jdbc:postgresql://+System.getenv("TRAINING_DB_ENDPOINT")+/+System.getenv("TRAINING_DB_DATABASENAME");
    username: System.getenv("TRAINING_DB_USERNAME");
    password: System.getenv("TRAINING_DB_PASSWORD");
    driver-class-name: org.postgresql.Driver
  sql:
   init:
      data-locations:
      - classpath:./teamdata.sql
      mode: always
    
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop